name: ella-smsc
title: Ella SMSC
base: core26
adopt-info: smsc-release-data
summary: Ella SMSC is a secure, reliable, and easy to operate SMS service center.
description: |
  Ella SMSC lets private cellular network subscribers send and receive SMS messages. It is an SMS Service Center (SMSC) that integrates with 4G and 5G core networks.

source-code: https://github.com/ellanetworks/smsc
issues:
  - https://github.com/ellanetworks/smsc/issues
website:
  - https://docs.ellanetworks.com
grade: stable
confinement: strict
license: BUSL-1.1
icon: snap/gui/icon.svg

apps:
  smscd:
    daemon: simple
    install-mode: disable
    command: bin/smsc --config $SNAP_COMMON/smsc.yaml
    restart-condition: on-failure
    plugs:
      - network-bind

parts:
  smsc:
    plugin: go
    source: .
    source-type: local
    build-packages:
      - gcc
      - git
    build-snaps:
      - go/1.26/stable
      - node/24/stable
    override-build: |
      npm ci --prefix ui
      npm run build --prefix ui
      REVISION=`git rev-parse HEAD`
      go build -v -o ${CRAFT_PART_INSTALL}/bin/smsc -ldflags "-s -w -X github.com/ellanetworks/smsc/version.GitCommit=${REVISION}" ./cmd/smsc

  config:
    plugin: dump
    source: snap/local

  smsc-release-data:
    plugin: nil
    source: .
    override-build: |
      version="$(cat version/VERSION)"
      craftctl set version="$version"
