name: Image Build

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-26.04-arm') || 'ubuntu-26.04' }}
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: canonical/craft-actions/rockcraft/pack@57ce4083bf8bfad3ea1aacd8fb9474eff4480732 # main
        id: rockcraft
        with:
          channel: stable

      - name: Save container image to file
        run: |
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${rock_file}" docker-daemon:ella-smsc:latest
          docker save -o ellasmsc_latest-${{ matrix.arch }}.tar ella-smsc:latest

      - name: Upload container image to GitHub Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ellasmsc-image-${{ matrix.arch }}
          path: ellasmsc_latest-${{ matrix.arch }}.tar
