name: Main workflow

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  go-unit-test:
    uses: ./.github/workflows/go-unittest.yaml
  go-lint:
    uses: ./.github/workflows/go-lint.yaml
  ui-lint:
    uses: ./.github/workflows/ui-lint.yaml
  ui-typecheck:
    uses: ./.github/workflows/ui-typecheck.yaml
  ui-test:
    uses: ./.github/workflows/ui-test.yaml
  image-build:
    uses: ./.github/workflows/image-build.yaml
  snap-build:
    uses: ./.github/workflows/snap-build.yaml
  snap-strict-test:
    needs: [snap-build]
    uses: ./.github/workflows/snap-strict-test.yaml
  image-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [go-unit-test, go-lint, ui-lint, ui-typecheck, ui-test, image-build]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/image-publish.yaml
  snap-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [go-unit-test, go-lint, ui-lint, ui-typecheck, ui-test, snap-build, snap-strict-test]
    uses: ./.github/workflows/snap-publish.yaml
    secrets:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
